# Generated by Django 5.0 on 2025-09-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
